# Generated by Django 4.0.2 on 2022-03-01 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RESPONSABILE', 'Responsable'), ('CONTRIBUTOR', 'Contibuteur')], max_length=30, verbose_name='Role')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(max_length=2048)),
                ('type', models.CharField(choices=[('back-end', 'Back-end'), ('front-end', 'front-end'), ('Ios', 'Ios'), ('android', 'Android')], max_length=30, verbose_name='Type')),
                ('author_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('role', models.ManyToManyField(related_name='role', through='project.Contributor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(max_length=2048)),
                ('tag', models.CharField(choices=[('bug', 'Bug'), ('improvement', 'Amélioration'), ('task', 'Tâche')], max_length=30, verbose_name='Tag')),
                ('priority', models.CharField(choices=[('weak', 'Faible'), ('average', 'Moyenne'), ('high', 'Elevée')], max_length=30, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('to do', 'A faire'), ('in progress', 'En cours'), ('done', 'Terminée')], max_length=30, verbose_name='Statut')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('assignee_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asssigned', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur assigné')),
                ('author_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='project.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Problème',
                'verbose_name_plural': 'Problèmes',
            },
        ),
        migrations.AddField(
            model_name='contributor',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2048)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('author_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('issues_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='project.issue')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
            },
        ),
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together={('user_id', 'project_id')},
        ),
    ]
