# Generated by Django 4.0.2 on 2022-02-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_comments_comment_rename_issues_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('WEAK', 'Faible'), ('AVERAGE', 'Moyenne'), ('HIGH', 'Elevée')], max_length=30, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'A faire'), (' IN_PROGRESS', 'En cours'), ('DONE', 'Terminé')], max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('BUG', 'Bug'), ('IMPROVEMENT', 'Amélioration'), ('TASK', 'Tâche')], max_length=30, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('BACKEND', 'back-end'), ('FRONTEND', 'front-end'), ('IOS', 'iOS'), ('ANDROID', 'Android')], max_length=30, verbose_name='Type'),
        ),
    ]
