# Generated by Django 4.0.2 on 2022-03-01 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_remove_project_role_project_users_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={'verbose_name': 'Contributeur', 'verbose_name_plural': 'Contributeurs'},
        ),
        migrations.AlterField(
            model_name='project',
            name='author_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
    ]
