# Generated by Django 4.0.2 on 2022-03-01 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_contributor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={'verbose_name': 'Contributeur', 'verbose_name_plural': 'contributeurs'},
        ),
        migrations.AlterField(
            model_name='issue',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='project.project'),
        ),
    ]
