# Generated by Django 4.0.2 on 2022-02-22 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_issue_title_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Project'),
            preserve_default=False,
        ),
    ]
